In [1]:
import numpy as np

In [8]:
v = np.array([[1, 2, 3, 4]]).T

S = np.array([
    [4, 3, 6, 2],
    [0, 4, 0, 1]
]).T

T = np.array([
    [1, 2, 2, 2],
    [0, 0, 1, 2]
]).T

In [16]:
Sv = np.concatenate((S, v), axis=1)
Tv = np.concatenate((T, v), axis=1)

print(Sv, end='\n\n')
print(Tv)

[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]


In [19]:
print(f'Rank of S : {np.linalg.matrix_rank(S)}')
print(f'Rank of T : {np.linalg.matrix_rank(T)}')

Rank of S : 2
Rank of T : 2


In [18]:
print(f'Rank of Sv : {np.linalg.matrix_rank(Sv)}')
print(f'Rank of Tv : {np.linalg.matrix_rank(Tv)}')

Rank of Sv : 3
Rank of Tv : 2
