In [1]:
import numpy as np

In [13]:
m = 3

M1 = np.random.randn(m, m)
M1 = M1 @ M1.T

M2 = np.random.randn(m, m)
M2 = M2 @ M2.T

In [19]:
if np.sum(M1 - M1.T) == 0:
    print("M1 is a symmetric matrix.")
else:
    print("M1 is not a symmetric matrix.")

M1 is a symmetric matrix.


In [18]:
if np.sum(M2 - M2.T) == 0:
    print("M2 is a symmetric matrix.")
else:
    print("M2 is not a symmetric matrix.")

M2 is a symmetric matrix.


In [20]:
M1sM2 = M1 + M2
M1mM2 = M1 @ M2
M1hM2 = M1 * M2

In [22]:
print(M1sM2 - M1sM2.T)
print(M1mM2 - M1mM2.T)
print(M1hM2 - M1hM2.T)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  0.          -9.6736658   -2.82552552]
 [  9.6736658    0.         -11.60040684]
 [  2.82552552  11.60040684   0.        ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
