In [19]:
import numpy as np

In [22]:
m = 4

A = np.random.randn(m, m)
B = np.diag(np.random.randn(m))

print(A, end='\n\n')
print(B)

[[-0.59874794 -1.19772612  2.56219608 -1.86329341]
 [ 0.82160384 -0.6213755   0.468481    0.07166996]
 [-0.00905104  0.39649765 -0.51883249 -0.59727455]
 [ 0.51463489 -0.26789534  0.19499411  1.32349414]]

[[ 0.10942353  0.          0.          0.        ]
 [ 0.         -2.00909748  0.          0.        ]
 [ 0.          0.          0.38525038  0.        ]
 [ 0.          0.          0.         -1.11665825]]


In [23]:
A*A

array([[3.58499092e-01, 1.43454786e+00, 6.56484877e+00, 3.47186232e+00],
       [6.75032869e-01, 3.86107513e-01, 2.19474451e-01, 5.13658331e-03],
       [8.19213784e-05, 1.57210387e-01, 2.69187151e-01, 3.56736882e-01],
       [2.64849072e-01, 7.17679120e-02, 3.80227026e-02, 1.75163675e+00]])

In [24]:
A@A

array([[-1.60766363,  2.97644605, -3.78790336, -2.96659031],
       [-0.96981448, -0.4313973 ,  1.58491958, -1.76037998],
       [ 0.02850094, -0.28124205,  0.3152832 , -0.4353222 ],
       [ 0.15111095, -0.72717126,  1.34999591,  0.65705588]])

In [25]:
B*B

array([[0.01197351, 0.        , 0.        , 0.        ],
       [0.        , 4.03647267, 0.        , 0.        ],
       [0.        , 0.        , 0.14841786, 0.        ],
       [0.        , 0.        , 0.        , 1.24692565]])

In [26]:
B@B

array([[0.01197351, 0.        , 0.        , 0.        ],
       [0.        , 4.03647267, 0.        , 0.        ],
       [0.        , 0.        , 0.14841786, 0.        ],
       [0.        , 0.        , 0.        , 1.24692565]])

In [27]:
B*B - B@B 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])