In [1]:
import numpy as np

In [8]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix

print(d)
print()
print(D)
print()

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )

print(tr)
print()
print(tr2)

[ 0.  7. -3.  0.]

[[ 0.  0.  0.  0.]
 [ 0.  7.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  0.]]

4.0

4.0
