In [1]:
import numpy as np

In [10]:
# square vs. rectangular
S = np.random.randn(3,3)
R = np.random.randn(3,2) # 5 rows, 2 columns
print(S)
print('')
print(R)

[[ 0.73087536 -0.36856748  1.18069384]
 [ 1.56143294 -0.8075863   0.05648548]
 [-1.0859959  -1.13709918 -1.90218103]]

[[ 0.14633733 -2.47807732]
 [ 1.42563339 -0.29700109]
 [-0.44649575 -0.29717529]]


In [3]:
# identity
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# zeros
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [12]:
# Extract diadonal elements
D_vec = np.diag(D)
print(D_vec)

[1 2 3 5 2]


In [14]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(U)
print('')
print(L)

[[-0.75314163 -1.29312556  1.10540394  0.11339644 -0.18913071]
 [ 0.          0.13561009 -0.19325962  0.01208004  2.04961443]
 [ 0.          0.          0.7172417   0.3893882  -0.65536171]
 [ 0.          0.          0.          1.0682408  -0.86859316]
 [ 0.          0.          0.          0.          1.35412575]]

[[-0.75314163  0.          0.          0.          0.        ]
 [ 0.31169619  0.13561009  0.          0.          0.        ]
 [ 0.71007928 -0.51254049  0.7172417   0.          0.        ]
 [ 1.79942681  1.21108586  0.92595698  1.0682408   0.        ]
 [ 0.04899766 -0.59184358 -1.90803938  0.58807838  1.35412575]]


In [7]:
# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.25691315 -1.63314924 -0.5945582  -0.23138909  1.51846735  1.00080379]
 [-0.86197065 -0.78136553  0.49940909 -0.10563009  1.46602037  0.13252572]
 [-0.36244385 -0.31076063  1.09041569  1.27835894 -0.90300508  1.88208083]]
