In [2]:
import numpy as np

In [5]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,4)

# try to add them
print(A+B)
print(A+C)

[[ 0.92059049 -2.13279298  0.70736533  0.34476837]
 [ 0.29288599 -0.49129921  3.41252501  1.04766483]
 [-1.34883515  0.27519824  0.03895976  0.7886062 ]
 [ 2.13300796 -1.34822662 -1.19623517  2.06603711]
 [-1.72672529 -0.9781296  -0.60089551  3.50800616]]
[[ 1.59751981 -1.24006746 -0.57695386 -1.16850628]
 [ 0.52241607  0.3126001   3.03876782  1.90107452]
 [ 0.20292563  1.26236355 -0.60147217  0.09440214]
 [ 1.98589135 -1.00257921  1.79433159  1.46851883]
 [-1.3261199   0.17547011  1.71122379  1.23963107]]


In [9]:
# "shifting" a matrix
l = .3 # lambda
N = 3  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(np.concatenate((D, Ds), axis=1))

[[ 1.95048592  2.33116035  1.25384412  2.25048592  2.33116035  1.25384412]
 [-1.51484287  0.10721748 -2.32192866 -1.51484287  0.40721748 -2.32192866]
 [-0.96921088 -0.3676867   1.10267732 -0.96921088 -0.3676867   1.40267732]]
