In [1]:
import numpy as np

## My solution

In [16]:
M, N = 3, 2

s = np.random.randint(-10,10,1)

A = np.random.randint(-10, 10, (M,N))
B = np.random.randint(-10, 10, (M,N))

sAB = s*(A + B)
sAsB = s*A + s*B

print(sAB)
print()
print(sAsB)

if np.sum(sAB == sAsB) == M*N:
    print("s(A+B) is equal to sA+sB")
else:
    print("s(A+B) is not equal to sA+sB")

[[ 56 -77]
 [ 42 -63]
 [ 21  21]]

[[ 56 -77]
 [ 42 -63]
 [ 21  21]]
s(A+B) is equal to sA+sB


## Course solution

In [20]:
M, N = 3, 2

s = np.random.randn(1)

A = np.random.randn(M,N)
B = np.random.randn(M,N)

sAB = s*(A + B)
sAsB = s*A + s*B

print(sAB)
print()
print(sAsB)
print()
print(sAB - sAsB)

[[ 2.54339925 -6.7974371 ]
 [ 3.32705719 -2.01375479]
 [-2.26330055 -3.02786697]]

[[ 2.54339925 -6.7974371 ]
 [ 3.32705719 -2.01375479]
 [-2.26330055 -3.02786697]]

[[ 0.0000000e+00  0.0000000e+00]
 [ 4.4408921e-16  4.4408921e-16]
 [-4.4408921e-16  4.4408921e-16]]
