In [1]:
import numpy as np

In [11]:
M = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(M.T, end='\n\n')
print(M.T.T)

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


In [32]:
C = np.array(
    [
        [ np.complex(4, 1), 3, np.complex(2, -4)]
    ]
)

print(C, end='\n\n')
print(C.T, end='\n\n') # normal transpose
print(np.transpose(C), end='\n\n') # normal transpose
print(C.conj().T) # Hermitian transpose( sign of the complex part flip )

[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
