# Import

In [1]:
import numpy as np

# My solution

In [2]:
# Two 4x6 matrices of random numbers
m1 = np.floor(np.random.uniform(-10,10,size=(4,6))).astype(int)
m2 = np.floor(np.random.uniform(-10,10,size=(4,6))).astype(int)

#Dot product to compute corresponding columns
ans1 = np.zeros(6)
ans2 = np.zeros(6)

for i in range(6):
    for j in range(4):
        ans1[i] = ans1[i] + m1[j,i]*m2[j,i]


for i in range(6):
    ans2[i] = np.sum(m1[:,i]*m2[:,i])

ans1, ans2

(array([-29., -60.,  -7.,  -7., -41., 131.]),
 array([-29., -60.,  -7.,  -7., -41., 131.]))

# Course solution

In [3]:
A = np.random.randn(4,6)
B = np.random.randn(4,6)

dps = np.zeros(np.size(A,1))

for i in range(np.size(A,1)):
    dps[i] = np.dot(A[:,i], B[:,i])

dps

array([ 0.26560712, -0.75491299,  0.04664566,  0.48472876,  0.32544416,
        1.20187126])